services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-center-platform
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "true"
      DB_INIT_MODE: migrations_only
    ports:
      - "2000:80"
      - "2001:3150"
    restart: unless-stopped
